### ISSUE TITLE
Errors in current pricing?

### ISSUE THREAD

**Issue by kbekus** [contre95/controtto#20]
hey there,  I like your application and am keen to use it but I'm wondering if there might be a value overflow or calculation error somewhere?  For example, a transaction like the following:

Bought 943396 SLP on 27/10/2022 for approx. 2 ETH
![image](https://github.com/contre95/controtto/assets/99165155/1404ab6b-7b57-4fb8-b97b-7b893f613eb4)

Now it's calculating the value at:
![image](https://github.com/contre95/controtto/assets/99165155/fb949c29-2c9d-4a20-9425-0737a7a06da4)

It seems to think 1 SLP is worth 878,763 ETH (I wish). I've got a couple of other examples like this if it helps.

**Comment by contre95** [comment]
Glad you like the application.
I'll be checking it this weekend. Thanks for rising the issue :)

**Comment by contre95** [comment]
I think it was just a[ small issue](https://github.com/contre95/controtto/commit/b54675432403db6820f88daf9f9d75720d1410eb) with the BingX module while calculating the price of an Base Assets based on a Quote that's not USD/USDT. 

It should work now. I uploaded a [new image to docker](https://hub.docker.com/r/contre95/controtto) with the fix.
